### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by TheDarkTrumpet** [FSCL/FSCL.Compiler#7]
Hello,

I just checked out this project, and tried to build it (build.sh) and I'm getting a lot of build errors.  This weekend, I may be able to try and look into more why this is happening, but I figured it worth giving what I ran into now.

wireless-nat-inside:FSCL.Compiler dthole$ fsharpc --version
F# Compiler for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

The build errors I'm getting are:

/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(101,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(104,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(118,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(121,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(136,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(144,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(156,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(159,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(174,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(177,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(192,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(195,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(210,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(213,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(228,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(231,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(246,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/KernelContextTest.fs(249,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(171,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(174,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(188,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(191,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(205,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(208,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(222,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(225,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(239,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(250,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(261,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(264,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(278,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(281,12): error FS0039: The field, constructor or member 'NotNull' is not defined
/Users/dthole/Programming/FSCL.Compiler/tests/FSCL.Compiler.Tests/FunctionContextTest.fs(295,12): error FS0039: The field, constructor or member 'NotNull' is not defined

**Comment by GabrieleCocco** [comment]
Hi. I'm currently trying to solve this issue. The problem is related to the F# scaffold "build" toolchain when compiling the unit tests. Try using xbuild (xbuild FSCL.Compiler.sln), should work properly.
